-- AlterTable
ALTER TABLE "public"."punches" ALTER COLUMN "event_time" SET DATA TYPE TIMESTAMPTZ(0),
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ(0),
ALTER COLUMN "corrected_at" SET DATA TYPE TIMESTAMPTZ(0),
ALTER COLUMN "correct_event_time" SET DATA TYPE TIMESTAMPTZ(0);
